server:
  type: simple
  rootPath: /api/*
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080
validPairs:
  - GBPUSD
  - GBPEUR
  - GBPCAD
  - GBPAUD
  - USDCHF
  - EURUSD
  - GBPCHF
  - AUDUSD
  - EURAUD
  - NZDAUD
  - NZDGBP
