logging:
  level: WARN
  loggers:
    io.dropwizard: WARN
    com.scottlogic: DEBUG
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
      logFormat: "%d %p %C %L %m%n"
server:
  type: simple
  rootPath: /api/*
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 80
clientBroadcastMillis: 500
validPairs:
  GBPUSD:
    id: GBPUSD
    decimals: 5
  GBPEUR:
    id: GBPEUR
    decimals: 5
  GBPCAD:
    id: GBPCAD
    decimals: 5
  GBPAUD:
    id: GBPAUD
    decimals: 5
  USDCHF:
    id: USDCHF
    decimals: 5
  EURUSD:
    id: EURUSD
    decimals: 5
  GBPCHF:
    id: GBPCHF
    decimals: 5
  AUDUSD:
    id: AUDUSD
    decimals: 5
  EURAUD:
    id: EURAUD
    decimals: 5
  NZDAUD:
    id: NZDAUD
    decimals: 5
  NZDGBP:
    id: NZDGBP
    decimals: 5
priceConfigurations:
  GBPUSD:
   basePrice: 134000
   broadcastFrequencyMillis: 250
  GBPEUR:
   basePrice: 121000
   broadcastFrequencyMillis: 250
  GBPCAD:
   basePrice: 174000
   broadcastFrequencyMillis: 5000
  GBPAUD:
   basePrice: 180000
   broadcastFrequencyMillis: 5000
  USDCHF:
   basePrice:  97000
   broadcastFrequencyMillis: 1000
  EURUSD:
   basePrice: 111000
   broadcastFrequencyMillis: 250
  GBPCHF:
   basePrice: 131000
   broadcastFrequencyMillis: 1000
  AUDUSD:
   basePrice:  75000
   broadcastFrequencyMillis: 1000
  EURAUD:
   basePrice: 149000
   broadcastFrequencyMillis: 1000
  NZDAUD:
   basePrice:   95000
   broadcastFrequencyMillis: 60000
  NZDGBP:
   basePrice:   53000
   broadcastFrequencyMillis: 30000
