logging:
  level: WARN
  loggers:
    io.dropwizard: WARN
    com.scottlogic: DEBUG
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
      logFormat: "%d %p %C %L %m%n"
server:
  type: simple
  rootPath: /api/*
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080
validPairs:
  - eurgbp
  - eurusd
  - gbpusd
  - eurjpy
priceHistoryResolutions:
  - 10000
  - 60000
  - 300000
testPrices:
  eurgbp: 0.77
  eurusd: 1.13
  gbpusd: 1.47
  eurjpy: 117.84
  