logging:
  level: WARN
  loggers:
    io.dropwizard: WARN
    com.scottlogic: DEBUG
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
      logFormat: "%d %p %C %L %m%n"
server:
  type: simple
  rootPath: /api/*
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 80
validPairs:
  GBPUSD:
    id: GBPUSD
    decimals: 5
  GBPEUR:
    id: GBPEUR
    decimals: 5
  GBPCAD:
    id: GBPCAD
    decimals: 5
  GBPAUD:
    id: GBPAUD
    decimals: 5
  USDCHF:
    id: USDCHF
    decimals: 5
  EURUSD:
    id: EURUSD
    decimals: 5
  GBPCHF:
    id: GBPCHF
    decimals: 5
  AUDUSD:
    id: AUDUSD
    decimals: 5
  EURAUD:
    id: EURAUD
    decimals: 5
  NZDAUD:
    id: NZDAUD
    decimals: 5
  NZDGBP:
    id: NZDGBP
    decimals: 5
testPrices:
  GBPUSD: 134000
  GBPEUR: 121000
  GBPCAD: 174000
  GBPAUD: 180000
  USDCHF:  97000
  EURUSD: 111000
  GBPCHF: 131000
  AUDUSD:  75000
  EURAUD: 149000
  NZDAUD:  95000
  NZDGBP:  53000
priceFeedMillis: 100
clientBroadcastMillis: 1000
