logging:
  level: WARN
  loggers:
    io.dropwizard: WARN
    com.scottlogic: DEBUG
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
      logFormat: "%d %p %C %L %m%n"
server:
  type: simple
  rootPath: /api/*
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080
template: Hello, %s!!!
defaultName: GradTrader
